tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash-completion"
brew "git"
brew "sqlite"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ios-webkit-debug-proxy", args: ["HEAD"]
brew "mongodb"
brew "mysql"
brew "node"
brew "postgresql"
brew "redis"
brew "thefuck"
brew "wget"
brew "yarn"
cask "alfred"
cask "docker"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "mysqlworkbench"
cask "postgres"
cask "postman"
cask "psequel"
cask "robo-3t"
cask "sequel-pro"
cask "slack"
cask "spectacle"
cask "spotify"
cask "teamviewer"
cask "visual-studio-code"
